name: 'Frontend: Publish'

on:
  push:
    branches: ['master', 'main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: valitydev/action-setup-thrift@v1
      - uses: valitydev/action-frontend/setup-install@v2
        with:
          npm-not-ci: true
      - name: Build
        run: npm run codegen
      - uses: valitydev/action-frontend/publish@v2
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
